tap "homebrew/bundle"
brew "atuin"
brew "bat"
brew "dust"
brew "eza"
brew "fd"
brew "ffmpeg"
brew "helix"
brew "htop"
brew "jq"
brew "lazygit"
brew "mas"
brew "mise"
brew "neovim"
brew "neovide"
brew "nmap"
brew "pyright"
brew "ripgrep"
brew "sk"
brew "stow"
brew "trash"
brew "unzip"
brew "vscode-langservers-extracted"
brew "zellij"
brew "zoxide"
cask "blender"
cask "discord"
cask "ea"
cask "firefox"
cask "font-jetbrains-mono-nerd-font"
cask "ghidra"
cask "godot"
cask "iterm2"
cask "obsidian"
cask "preform"
cask "prusaslicer"
cask "shadow"
cask "steam"
cask "vagrant"
cask "vlc"
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "The Unarchiver", id: 425424353
mas "Xcode", id: 497799835
